#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-next

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-      
    - name: Set up JDK 11
      uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
      with:
        distribution: 'adopt'
        java-version: '11.0.11+9'
    - name: Login to docker.io
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: docker.io
    - name: Login to quay.io
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Build docker images
      id: build
      run: |
        set -xe
        SHORT_SHA1=$(git rev-parse --short HEAD)
        echo ::set-output name=short_sha1::${SHORT_SHA1}
        
        cd tests/e2e
        docker build -t quay.io/eclipse/che-e2e:next -f build/dockerfiles/Dockerfile .
        docker tag quay.io/eclipse/che-e2e:next quay.io/eclipse/che-e2e:${SHORT_SHA1}
    - name: Push docker images
      run: |
        docker push quay.io/eclipse/che-e2e:next
        docker push quay.io/eclipse/che-e2e:${{ steps.build.outputs.short_sha1 }}
    - name: Create failure MM message
      if: ${{ failure() }}
      run: |
        echo "{\"text\":\":no_entry_sign: Next Che E2E build has failed: https://github.com/eclipse/che/actions/workflows/next-build.yml\"}" > mattermost.json
    - name: Send MM message
      if: ${{ failure() }}
      uses: mattermost/action-mattermost-notify@826343e28f7ff679a883b01161387142ee429a85
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-ci
        MATTERMOST_USERNAME: che-bot
